import { UserData } from "./user"

export interface LeagueData {
	name: string
	status: string
	metadata: LeagueMetadata
	settings: LeagueSettings
	avatar: any
	company_id: any
	shard: number
	season: string
	season_type: string
	sport: string
	scoring_settings: LeagueScoringSettings
	last_message_id: string
	last_author_avatar: any
	last_author_display_name: string
	last_author_id: string
	last_author_is_bot: boolean
	last_message_attachment: any
	last_message_text_map: any
	last_message_time: number
	last_pinned_message_id: any
	draft_id: string
	last_read_id: any
	league_id: string
	previous_league_id: any
	bracket_id: any
	bracket_overrides_id: any
	group_id: any
	roster_positions: string[]
	loser_bracket_id: any
	loser_bracket_overrides_id: any
	total_rosters: number
	users: UserData[]
}

export interface LeagueMetadata {
	auto_continue: string
	keeper_deadline: string
	latest_league_winner_roster_id: string
}

export interface LeagueSettings {
	best_ball: number
	last_report: number
	waiver_budget: number
	disable_adds: number
	divisions: number
	capacity_override: number
	waiver_bid_min: number
	taxi_deadline: number
	draft_rounds: number
	reserve_allow_na: number
	start_week: number
	playoff_seed_type: number
	playoff_teams: number
	veto_votes_needed: number
	squads: number
	num_teams: number
	daily_waivers_hour: number
	playoff_type: number
	taxi_slots: number
	sub_start_time_eligibility: number
	last_scored_leg: number
	daily_waivers_days: number
	sub_lock_if_starter_active: number
	playoff_week_start: number
	waiver_clear_days: number
	reserve_allow_doubtful: number
	commissioner_direct_invite: number
	veto_auto_poll: number
	reserve_allow_dnr: number
	taxi_allow_vets: number
	waiver_day_of_week: number
	playoff_round_type: number
	reserve_allow_out: number
	reserve_allow_sus: number
	veto_show_votes: number
	trade_deadline: number
	taxi_years: number
	daily_waivers: number
	faab_suggestions: number
	disable_trades: number
	pick_trading: number
	type: number
	max_keepers: number
	waiver_type: number
	max_subs: number
	league_average_match: number
	trade_review_days: number
	bench_lock: number
	offseason_adds: number
	leg: number
	reserve_slots: number
	reserve_allow_cov: number
	daily_waivers_last_ran: number
}

export interface LeagueScoringSettings {
	sack: number
	qb_hit: number
	fgm_40_49: number
	bonus_rec_te: number
	fgm_yds: number
	def_forced_punts: number
	bonus_rec_yd_100: number
	bonus_rush_yd_100: number
	pass_int: number
	fgmiss_50p: number
	pts_allow_0: number
	bonus_pass_yd_400: number
	pass_2pt: number
	rec_0_4: number
	yds_allow_450_499: number
	blk_kick_ret_yd: number
	st_td: number
	def_pr_yd: number
	rec_30_39: number
	sack_yd: number
	fgm_yds_over_30: number
	rec_td: number
	yds_allow_400_449: number
	tkl_ast: number
	rec_20_29: number
	idp_blk_kick: number
	fgm_30_39: number
	fgm_50_59: number
	idp_fum_ret_yd: number
	xpmiss: number
	rush_td_50p: number
	rush_td: number
	def_kr_yd: number
	bonus_fd_wr: number
	pts_allow: number
	def_4_and_stop: number
	fg_ret_yd: number
	idp_tkl: number
	yds_allow_550p: number
	pass_td_40p: number
	def_st_tkl_solo: number
	yds_allow_350_399: number
	fgm: number
	idp_sack_yd: number
	bonus_rush_rec_yd_100: number
	rec_2pt: number
	bonus_pass_cmp_25: number
	idp_tkl_loss: number
	rush_fd: number
	pass_int_td: number
	int_ret_yd: number
	idp_tkl_solo: number
	pass_att: number
	st_fum_rec: number
	fgmiss: number
	bonus_def_fum_td_50p: number
	ff: number
	idp_int: number
	bonus_sack_2p: number
	fgmiss_30_39: number
	rec: number
	yds_allow_200_299: number
	idp_int_ret_yd: number
	idp_safe: number
	pts_allow_14_20: number
	def_2pt: number
	fgm_0_19: number
	idp_def_td: number
	idp_pass_def_3p: number
	int: number
	def_st_fum_rec: number
	fum_lost: number
	pts_allow_1_6: number
	rec_fd: number
	kr_yd: number
	fgm_60p: number
	fgmiss_20_29: number
	rush_att: number
	st_tkl_solo: number
	yds_allow: number
	rec_5_9: number
	idp_sack: number
	fgm_20_29: number
	fgmiss_60p: number
	yds_allow_500_549: number
	pts_allow_21_27: number
	bonus_rec_wr: number
	bonus_pass_yd_300: number
	xpm: number
	pass_td_50p: number
	pass_sack: number
	rec_40p: number
	def_3_and_out: number
	fgmiss_50_59: number
	fgmiss_0_19: number
	pass_cmp: number
	tkl_loss: number
	rush_2pt: number
	def_pass_def: number
	yds_allow_300_349: number
	fum_rec: number
	idp_pass_def: number
	rec_10_19: number
	bonus_rec_yd_200: number
	def_st_td: number
	tkl: number
	pass_cmp_40p: number
	fgm_50p: number
	bonus_tkl_10p: number
	def_td: number
	idp_fum_rec: number
	pass_fd: number
	rec_td_40p: number
	bonus_rush_yd_200: number
	safe: number
	pass_yd: number
	fgmiss_40_49: number
	rec_td_50p: number
	blk_kick: number
	pass_td: number
	tkl_solo: number
	bonus_rush_att_20: number
	yds_allow_100_199: number
	bonus_def_int_td_50p: number
	idp_qb_hit: number
	bonus_fd_qb: number
	rush_yd: number
	yds_allow_0_100: number
	bonus_rec_rb: number
	rush_40p: number
	pr_yd: number
	fum: number
	pts_allow_28_34: number
	pts_allow_35p: number
	bonus_rush_rec_yd_200: number
	fum_rec_td: number
	rec_yd: number
	rush_td_40p: number
	bonus_fd_te: number
	bonus_fd_rb: number
	fum_ret_yd: number
	def_st_ff: number
	pass_inc: number
	pts_allow_7_13: number
	idp_ff: number
	st_ff: number
	idp_tkl_ast: number
}
